name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: 19

      - name: Set plugin version
        run: version='${{ github.event.release.tag_name }}' && sed -i "s/0\.0\.0/${version:10}/" gradle.properties
        shell: bash

      - name: Build with Gradle
        shell: bash
        run: |
          mkdir package
          ./gradlew :daw:shadowJar
          cp daw/build/libs/daw.jar package/EchoInMirror.jar
          cp -R release-bin/. package/
          cp libEIMTimeStretchers.dll package/libEIMTimeStretchers.dll
          cp daw/EIMHost-x64.exe package/EIMHost-x64.exe
          curl https://github.com/EchoInMirror/EIMHost/releases/latest/download/EIMHost-x86.exe -o package/EIMHost-x86.exe -L
        env:
          APP_CENTER_SECRET: ${{ secrets.APP_CENTER_SECRET }}

      - name: Download ffmpeg
        shell: bash
        run: |
          curl https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip -O -L
          unzip ffmpeg-master-latest-win64-gpl.zip
          mkdir package/ffmpeg
          mv ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe package/ffmpeg/ffmpeg.exe

      - name: Download bellsoft jre
        shell: bash
        run: |
          curl https://download.bell-sw.com/java/19.0.2+9/bellsoft-jre19.0.2+9-windows-amd64.zip -O -L
          unzip -d ./package bellsoft-jre19.0.2+9-windows-amd64.zip
          mv package/jre-19.0.2 package/jre

      - name: Package
        run: |
          cp LICENSE package/LICENSE
          mv package EchoInMirror
          Compress-Archive -Path EchoInMirror -DestinationPath EchoInMirror.zip

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: EchoInMirror.zip
          asset_name: EchoInMirror-win64.zip
          tag: ${{ github.ref }}

      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: EchoInMirror/EchoInMirror.jar
          asset_name: EchoInMirror-win64.jar
          tag: ${{ github.ref }}
