name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: 17

      - name: Set plugin version
        run: version='${{ github.ref }}' && sed -i "s/0\.0\.0/${version:10}/" build.gradle.kts
        shell: bash

      - name: Build with Gradle
        run: |
          mkdir package
          ./gradlew :daw:shadowJar
          cp daw/build/libs/daw.jar package/EchoInMirror.jar
          cp release-bin/**/* package/
          curl https://github.com/EchoInMirror/EIMHost/releases/download/1.0.6/EIMHost.exe -o package/EIMHost.exe -L

      - name: Download ffmpeg
        run: |
          curl https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip -O -L
          unzip ffmpeg-master-latest-win64-gpl.zip
          mkdir package/ffmpeg
          mv ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe package/ffmpeg/ffmpeg.exe
        shell: bash

      - name: Decompress
        run: |
          curl https://cache-redirector.jetbrains.com/intellij-jbr/jbr-17.0.6-windows-x64-b802.4.tar.gz -O -L
          mkdir package/jbr;tar zxvf jbr_jcef-17.0.6-windows-x64-b802.4.tar.gz --strip-components 1 -C package/jbr

      - name: Package
        run: mv package EchoInMirror && Compress-Archive -Path EchoInMirror -DestinationPath EchoInMirror.zip
        shell: pwsh

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: EchoInMirror.zip
          asset_name: EchoInMirror-win64.zip
          tag: ${{ github.ref }}

      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: EchoInMirror/EchoInMirror.jar
          asset_name: EchoInMirror-win64.jar
          tag: ${{ github.ref }}
